server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  numberRegistrySyncRetries: 0
  instance:
    leaseRenewalIntervalInSeconds: 2