spring:
  application:
    name: "Das Client"

server:
  port: 8080
  application:
    name: client

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://54.194.242.215:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    se.omegapoint: DEBUG
