spring:
  application:
    name: "Competence Day Service"

server:
  port: 24703
  application:
    name: competenceday-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://54.194.242.215:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    se.omegapoint: DEBUG
