server:
  port: ${PORT:8761}

eureka:
  server:
    enable-self-preservation: false
    waitTimeInMsWhenSyncEmpty: 0
    registrySyncRetries: 0

  client:
    registerWithEureka: false
    fetchRegistry: false

  instance:
    leaseRenewalIntervalInSeconds: 2